<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="7" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="testing1" duration-ms="215194" started-at="2015-11-04T07:29:16Z" finished-at="2015-11-04T07:32:51Z">
    <groups>
      <group name="Mygroup">
        <method signature="CRUD.DeleteSO()[pri:4, instance:demo1.CRUD@1cc87e3]" name="DeleteSO" class="demo1.CRUD"/>
        <method signature="CRUD.EditSalesOrder()[pri:2, instance:demo1.CRUD@1cc87e3]" name="EditSalesOrder" class="demo1.CRUD"/>
        <method signature="CRUD.ViewSO()[pri:3, instance:demo1.CRUD@1cc87e3]" name="ViewSO" class="demo1.CRUD"/>
      </group> <!-- Mygroup -->
      <group name="Mygroup_2">
        <method signature="CRUD.SaleOrderACK()[pri:5, instance:demo1.CRUD@1cc87e3]" name="SaleOrderACK" class="demo1.CRUD"/>
        <method signature="CRUD.SalesOrderListing()[pri:6, instance:demo1.CRUD@1cc87e3]" name="SalesOrderListing" class="demo1.CRUD"/>
      </group> <!-- Mygroup_2 -->
    </groups>
    <test name="Test" duration-ms="215194" started-at="2015-11-04T07:29:16Z" finished-at="2015-11-04T07:32:51Z">
      <class name="demo1.CRUD">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:demo1.CRUD@1cc87e3]" name="beforeTest" is-config="true" duration-ms="40551" started-at="2015-11-04T12:59:16Z" finished-at="2015-11-04T12:59:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="AddSalesOrder()[pri:0, instance:demo1.CRUD@1cc87e3]" name="AddSalesOrder" duration-ms="34101" started-at="2015-11-04T12:59:57Z" finished-at="2015-11-04T13:00:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddSalesOrder -->
        <test-method status="FAIL" signature="SearchSaleOrder()[pri:1, instance:demo1.CRUD@1cc87e3]" name="SearchSaleOrder" duration-ms="33291" started-at="2015-11-04T13:00:31Z" finished-at="2015-11-04T13:01:04Z">
          <exception class="org.openqa.selenium.StaleElementReferenceException">
            <message>
              <![CDATA[Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 20.45 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'sakthivel-PC', ip: '172.16.11.74', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_40'
Session ID: 05f962ea-aa6b-4a68-becd-68a6c26badb1
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=32.0.3}]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 20.45 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'sakthivel-PC', ip: '172.16.11.74', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_40'
Session ID: 05f962ea-aa6b-4a68-becd-68a6c26badb1
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=32.0.3}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:326)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:178)
	at demo1.CRUD.SearchSaleOrder(CRUD.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'sakthivel-PC', ip: '172.16.11.74', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_40'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web-element-cache.js:9351)
	at <anonymous class>.Utils.getElementAt(file:///C:/Users/SAKTHI~1/AppData/Local/Temp/anonymous4979387694755123498webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:8978)
	at <anonymous class>.WebElement.getElementText(file:///C:/Users/SAKTHI~1/AppData/Local/Temp/anonymous4979387694755123498webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11965)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/SAKTHI~1/AppData/Local/Temp/anonymous4979387694755123498webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/SAKTHI~1/AppData/Local/Temp/anonymous4979387694755123498webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:621)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.StaleElementReferenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchSaleOrder -->
        <test-method status="PASS" signature="EditSalesOrder()[pri:2, instance:demo1.CRUD@1cc87e3]" name="EditSalesOrder" duration-ms="19691" started-at="2015-11-04T13:01:04Z" finished-at="2015-11-04T13:01:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EditSalesOrder -->
        <test-method status="PASS" signature="ViewSO()[pri:3, instance:demo1.CRUD@1cc87e3]" name="ViewSO" duration-ms="20973" started-at="2015-11-04T13:01:24Z" finished-at="2015-11-04T13:01:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ViewSO -->
        <test-method status="PASS" signature="DeleteSO()[pri:4, instance:demo1.CRUD@1cc87e3]" name="DeleteSO" duration-ms="22572" started-at="2015-11-04T13:01:45Z" finished-at="2015-11-04T13:02:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteSO -->
        <test-method status="PASS" signature="SaleOrderACK()[pri:5, instance:demo1.CRUD@1cc87e3]" name="SaleOrderACK" duration-ms="25561" started-at="2015-11-04T13:02:07Z" finished-at="2015-11-04T13:02:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SaleOrderACK -->
        <test-method status="PASS" signature="SalesOrderListing()[pri:6, instance:demo1.CRUD@1cc87e3]" name="SalesOrderListing" duration-ms="17992" started-at="2015-11-04T13:02:33Z" finished-at="2015-11-04T13:02:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SalesOrderListing -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:demo1.CRUD@1cc87e3]" name="afterTest" is-config="true" duration-ms="452" started-at="2015-11-04T13:02:51Z" finished-at="2015-11-04T13:02:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- demo1.CRUD -->
    </test> <!-- Test -->
  </suite> <!-- testing1 -->
</testng-results>
